// Common global sizing and values
const VIEWPORT_BREAK_WIDTH_PX = 600;
const STANDARD_PADDING_PX = 20;
const STANDARD_BORDER_RADIUS_PX = 5;

// The configuration side bar
const SIDEBAR_CONTENT_WIDTH_PX = 200;
const SIDEBAR_WIDTH_PX = SIDEBAR_CONTENT_WIDTH_PX + STANDARD_PADDING_PX * 2;

// Z-indices for tracking
const Z_INDEX_LOADING_INDICATOR = 10;
const Z_INDEX_SIDEBAR = 5;

export {
    VIEWPORT_BREAK_WIDTH_PX,
    STANDARD_PADDING_PX,
    STANDARD_BORDER_RADIUS_PX,
    SIDEBAR_WIDTH_PX,
    SIDEBAR_CONTENT_WIDTH_PX,
    Z_INDEX_LOADING_INDICATOR,
    Z_INDEX_SIDEBAR,
};